version: '3'
services:
    db:
        image: mysql:latest
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-rootpassword}   
            MYSQL_DATABASE: ${MYSQL_DATABASE:-mddapp}
            MYSQL_USER: ${MYSQL_USER:-mdduser}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD:-mddpassword}
        ports:
            - "3306:3306"
        volumes:
            - db_data:/var/lib/mysql
        networks:
            - mddapp_network
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
            interval: 10s
            timeout: 5s
            retries: 5
            start_period: 30s
    backend:
        build:
            context: ./back
            dockerfile: Dockerfile
        container_name: mdd-backend
        depends_on:
            db:
                condition: service_healthy
        env_file:
            - .env
        environment:
            APP_NAME: ${APP_NAME}
            SERVER_PORT: ${SERVER_PORT}
            API_PATH: ${API_PATH}
            SPRING_DATASOURCE_URL: ${MYSQL_DB_URL}
            SPRING_DATASOURCE_USERNAME: ${MYSQL_USER}
            SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASSWORD}
            JWT_SECRET_KEY: ${JWT_SECRET_KEY}
            JWT_EXPIRATION_TIME: ${JWT_EXPIRATION_TIME}
        ports:
         - "${SERVER_PORT}:8080"
        networks:
        - mddapp_network
        
volumes:
    db_data:
        driver: local
networks:
    mddapp_network:
        driver: bridge
        attachable: true
    